-- Insert team assignments
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (1, 62, 815, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (2, 107, 1838, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (3, 133, 2444, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (4, 30, 1950, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (5, 153, 1340, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (6, 146, 806, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (7, 123, 172, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (8, 57, 323, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (9, 59, 1276, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (10, 86, 2662, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (11, 147, 499, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (12, 107, 1983, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (13, 4, 1703, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (14, 18, 2097, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (15, 66, 630, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (16, 185, 674, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (17, 150, 572, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (18, 32, 274, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (19, 173, 1977, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (20, 178, 1390, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (21, 42, 1841, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (22, 12, 2320, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (23, 48, 312, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (24, 67, 506, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (25, 121, 2986, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (26, 25, 1894, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (27, 76, 205, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (28, 167, 162, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (29, 149, 1474, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (30, 155, 2196, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (31, 75, 2841, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (32, 95, 1570, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (33, 3, 2038, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (34, 124, 192, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (35, 195, 1336, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (36, 59, 1079, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (37, 3, 2831, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (38, 173, 660, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (39, 156, 22, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (40, 118, 1192, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (41, 200, 712, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (42, 176, 36, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (43, 196, 2572, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (44, 143, 1625, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (45, 154, 2978, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (46, 184, 1445, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (47, 19, 1150, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (48, 59, 978, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (49, 194, 849, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (50, 180, 2489, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (51, 89, 541, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (52, 38, 2564, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (53, 90, 45, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (54, 153, 1136, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (55, 9, 1578, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (56, 67, 2650, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (57, 47, 1166, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (58, 183, 2104, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (59, 64, 2886, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (60, 41, 2641, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (61, 29, 1159, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (62, 89, 1363, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (63, 199, 1584, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (64, 46, 1663, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (65, 2, 2238, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (66, 108, 2412, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (67, 89, 1393, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (68, 153, 186, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (69, 151, 1189, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (70, 167, 115, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (71, 50, 1445, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (72, 179, 392, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (73, 83, 171, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (74, 82, 2790, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (75, 36, 1310, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (76, 186, 1164, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (77, 16, 114, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (78, 105, 52, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (79, 74, 2974, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (80, 40, 1567, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (81, 70, 1112, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (82, 112, 287, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (83, 132, 1986, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (84, 197, 2936, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (85, 147, 1550, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (86, 58, 389, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (87, 196, 828, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (88, 50, 1817, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (89, 22, 2547, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (90, 166, 254, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (91, 8, 330, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (92, 147, 810, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (93, 44, 2089, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (94, 106, 893, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (95, 123, 2998, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (96, 23, 2553, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (97, 184, 2817, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (98, 81, 2934, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (99, 165, 2155, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (100, 19, 2391, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (101, 129, 2438, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (102, 105, 2665, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (103, 122, 2349, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (104, 66, 2052, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (105, 190, 2492, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (106, 81, 1713, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (107, 114, 2553, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (108, 12, 1897, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (109, 6, 325, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (110, 110, 2881, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (111, 102, 2256, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (112, 142, 699, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (113, 196, 2616, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (114, 90, 2991, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (115, 31, 1689, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (116, 23, 2749, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (117, 79, 1143, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (118, 157, 2844, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (119, 108, 2790, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (120, 194, 156, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (121, 172, 1744, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (122, 162, 2481, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (123, 15, 137, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (124, 38, 1318, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (125, 17, 181, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (126, 55, 1708, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (127, 27, 480, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (128, 4, 842, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (129, 130, 707, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (130, 196, 549, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (131, 77, 725, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (132, 2, 1761, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (133, 81, 2982, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (134, 66, 126, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (135, 20, 31, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (136, 66, 1232, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (137, 169, 2083, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (138, 37, 648, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (139, 125, 960, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (140, 169, 1572, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (141, 109, 2657, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (142, 136, 647, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (143, 1, 884, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (144, 121, 2130, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (145, 9, 2376, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (146, 34, 1236, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (147, 174, 1444, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (148, 76, 1625, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (149, 12, 2757, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (150, 142, 1387, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (151, 180, 2374, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (152, 125, 2371, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (153, 21, 2886, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (154, 23, 2608, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (155, 78, 1225, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (156, 68, 1401, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (157, 138, 2559, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (158, 65, 642, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (159, 157, 2380, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (160, 113, 2017, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (161, 112, 2187, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (162, 145, 1966, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (163, 144, 2016, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (164, 37, 1888, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (165, 27, 353, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (166, 193, 1427, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (167, 54, 2157, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (168, 93, 1279, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (169, 43, 2132, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (170, 134, 2961, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (171, 181, 1267, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (172, 143, 312, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (173, 74, 1243, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (174, 93, 2401, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (175, 52, 2125, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (176, 141, 2935, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (177, 116, 1920, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (178, 100, 969, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (179, 91, 1946, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (180, 126, 725, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (181, 187, 581, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (182, 25, 1327, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (183, 199, 2940, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (184, 74, 2472, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (185, 88, 1140, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (186, 102, 1336, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (187, 158, 2366, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (188, 192, 2936, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (189, 128, 76, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (190, 191, 2834, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (191, 192, 228, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (192, 82, 2384, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (193, 19, 1714, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (194, 80, 1055, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (195, 170, 1770, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (196, 3, 981, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (197, 58, 773, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (198, 153, 2967, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (199, 67, 368, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (200, 53, 2759, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (201, 133, 2855, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (202, 136, 1568, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (203, 75, 201, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (204, 56, 1242, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (205, 132, 1166, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (206, 36, 2413, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (207, 25, 172, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (208, 177, 2301, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (209, 4, 720, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (210, 52, 2092, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (211, 12, 2456, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (212, 13, 1122, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (213, 151, 2039, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (214, 82, 893, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (215, 59, 451, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (216, 15, 51, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (217, 169, 326, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (218, 71, 1653, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (219, 48, 2947, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (220, 200, 2559, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (221, 40, 2336, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (222, 101, 304, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (223, 37, 2527, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (224, 141, 2102, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (225, 19, 1126, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (226, 184, 1891, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (227, 143, 1344, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (228, 98, 2321, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (229, 142, 353, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (230, 62, 2555, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (231, 170, 1256, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (232, 127, 980, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (233, 11, 2694, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (234, 41, 189, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (235, 131, 2962, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (236, 171, 2397, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (237, 4, 987, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (238, 88, 1516, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (239, 31, 1027, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (240, 185, 2626, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (241, 179, 464, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (242, 95, 296, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (243, 16, 885, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (244, 50, 24, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (245, 17, 54, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (246, 27, 826, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (247, 98, 2560, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (248, 94, 2394, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (249, 125, 74, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (250, 191, 1298, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (251, 98, 2130, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (252, 197, 1487, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (253, 39, 2086, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (254, 60, 803, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (255, 48, 64, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (256, 61, 971, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (257, 6, 891, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (258, 195, 1617, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (259, 129, 2187, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (260, 11, 914, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (261, 96, 2839, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (262, 19, 378, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (263, 82, 2694, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (264, 181, 2800, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (265, 111, 436, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (266, 195, 103, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (267, 85, 225, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (268, 78, 1444, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (269, 171, 2133, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (270, 38, 2778, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (271, 6, 2520, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (272, 99, 2159, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (273, 43, 406, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (274, 55, 1116, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (275, 50, 1641, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (276, 70, 1989, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (277, 148, 528, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (278, 152, 624, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (279, 15, 1985, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (280, 113, 2057, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (281, 44, 1865, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (282, 68, 1789, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (283, 75, 2269, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (284, 86, 1508, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (285, 184, 405, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (286, 191, 418, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (287, 30, 2263, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (288, 160, 1609, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (289, 189, 1737, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (290, 104, 2424, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (291, 119, 1490, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (292, 199, 963, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (293, 34, 790, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (294, 57, 2158, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (295, 116, 329, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (296, 74, 1714, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (297, 44, 2424, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (298, 79, 1705, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (299, 120, 418, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (300, 98, 2525, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (301, 36, 1764, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (302, 184, 2325, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (303, 66, 497, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (304, 7, 1671, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (305, 79, 60, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (306, 31, 367, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (307, 19, 630, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (308, 22, 2037, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (309, 172, 1636, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (310, 121, 2081, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (311, 45, 2366, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (312, 131, 1834, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (313, 131, 2619, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (314, 55, 1454, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (315, 151, 2408, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (316, 29, 2907, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (317, 48, 1581, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (318, 183, 1710, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (319, 19, 2736, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (320, 24, 1448, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (321, 151, 2277, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (322, 6, 1582, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (323, 132, 1703, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (324, 147, 392, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (325, 169, 812, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (326, 134, 2243, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (327, 121, 1021, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (328, 58, 336, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (329, 121, 1855, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (330, 196, 1301, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (331, 62, 528, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (332, 50, 56, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (333, 144, 2095, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (334, 79, 379, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (335, 154, 2802, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (336, 89, 623, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (337, 66, 1905, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (338, 19, 2464, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (339, 36, 2044, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (340, 133, 1534, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (341, 105, 1808, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (342, 112, 1990, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (343, 138, 49, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (344, 195, 2952, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (345, 99, 2455, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (346, 136, 186, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (347, 82, 803, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (348, 88, 1672, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (349, 30, 289, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (350, 5, 2358, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (351, 3, 656, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (352, 190, 2714, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (353, 59, 445, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (354, 93, 2767, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (355, 143, 380, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (356, 171, 820, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (357, 71, 1029, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (358, 143, 2695, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (359, 111, 2203, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (360, 105, 2046, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (361, 137, 970, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (362, 124, 2448, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (363, 79, 296, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (364, 158, 477, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (365, 95, 1891, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (366, 37, 716, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (367, 137, 2594, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (368, 40, 1591, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (369, 123, 1041, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (370, 53, 798, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (371, 121, 2323, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (372, 195, 514, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (373, 76, 505, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (374, 183, 198, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (375, 62, 2102, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (376, 149, 1442, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (377, 12, 7, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (378, 139, 1190, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (379, 18, 55, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (380, 47, 164, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (381, 110, 141, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (382, 155, 2026, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (383, 77, 1648, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (384, 55, 1148, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (385, 40, 1994, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (386, 177, 1532, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (387, 13, 2470, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (388, 118, 1906, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (389, 167, 1731, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (390, 25, 87, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (391, 113, 2640, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (392, 149, 2367, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (393, 119, 1966, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (394, 75, 2757, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (395, 57, 640, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (396, 163, 866, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (397, 101, 1339, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (398, 133, 848, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (399, 138, 373, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (400, 71, 589, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (401, 13, 2865, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (402, 117, 225, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (403, 76, 949, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (404, 106, 2978, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (405, 55, 130, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (406, 64, 1295, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (407, 152, 1423, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (408, 190, 2762, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (409, 64, 237, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (410, 191, 2721, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (411, 151, 113, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (412, 45, 2380, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (413, 75, 243, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (414, 3, 1262, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (415, 46, 673, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (416, 24, 1521, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (417, 36, 815, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (418, 105, 101, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (419, 28, 690, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (420, 157, 2860, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (421, 166, 2271, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (422, 166, 440, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (423, 7, 1219, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (424, 1, 1374, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (425, 114, 1899, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (426, 144, 895, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (427, 18, 2242, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (428, 63, 1939, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (429, 139, 2743, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (430, 116, 2912, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (431, 184, 2905, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (432, 199, 1108, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (433, 98, 1053, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (434, 101, 1935, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (435, 146, 1040, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (436, 115, 1343, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (437, 146, 605, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (438, 151, 299, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (439, 38, 868, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (440, 6, 2867, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (441, 62, 2468, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (442, 77, 2501, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (443, 187, 776, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (444, 140, 582, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (445, 181, 1605, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (446, 182, 1023, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (447, 63, 2863, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (448, 193, 79, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (449, 195, 2157, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (450, 81, 1508, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (451, 49, 377, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (452, 158, 117, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (453, 45, 2344, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (454, 74, 2664, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (455, 160, 2561, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (456, 15, 1391, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (457, 30, 1808, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (458, 155, 673, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (459, 66, 1428, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (460, 143, 1844, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (461, 167, 2502, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (462, 134, 1262, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (463, 172, 2668, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (464, 107, 426, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (465, 169, 640, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (466, 155, 453, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (467, 162, 2707, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (468, 92, 1201, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (469, 74, 2701, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (470, 136, 692, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (471, 94, 1481, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (472, 179, 2898, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (473, 173, 310, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (474, 107, 2703, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (475, 118, 1607, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (476, 77, 1375, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (477, 27, 1457, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (478, 88, 2257, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (479, 20, 130, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (480, 87, 2125, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (481, 89, 600, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (482, 65, 1651, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (483, 139, 276, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (484, 91, 2182, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (485, 107, 2613, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (486, 53, 2182, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (487, 149, 951, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (488, 98, 2663, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (489, 171, 390, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (490, 95, 2837, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (491, 119, 805, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (492, 122, 2581, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (493, 47, 243, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (494, 120, 261, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (495, 175, 2348, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (496, 83, 38, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (497, 102, 1767, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (498, 147, 962, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (499, 64, 584, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (500, 130, 1465, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (501, 87, 548, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (502, 24, 1047, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (503, 170, 1812, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (504, 38, 1115, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (505, 147, 1634, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (506, 106, 583, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (507, 166, 181, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (508, 137, 1931, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (509, 131, 2802, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (510, 172, 1153, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (511, 40, 1009, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (512, 143, 2641, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (513, 120, 159, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (514, 6, 2399, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (515, 90, 790, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (516, 153, 2344, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (517, 175, 237, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (518, 129, 2554, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (519, 173, 1364, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (520, 173, 1451, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (521, 88, 1829, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (522, 9, 488, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (523, 126, 285, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (524, 157, 2949, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (525, 1, 1140, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (526, 189, 2021, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (527, 76, 1466, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (528, 130, 1114, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (529, 31, 2430, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (530, 143, 2899, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (531, 4, 2507, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (532, 185, 1445, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (533, 194, 1712, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (534, 26, 1573, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (535, 145, 1851, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (536, 22, 1114, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (537, 198, 2399, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (538, 199, 1319, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (539, 32, 2162, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (540, 32, 603, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (541, 104, 1085, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (542, 138, 2006, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (543, 54, 2392, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (544, 69, 170, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (545, 117, 2265, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (546, 110, 2304, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (547, 99, 2650, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (548, 134, 1600, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (549, 115, 1068, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (550, 133, 884, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (551, 110, 1963, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (552, 34, 1832, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (553, 90, 2681, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (554, 88, 197, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (555, 35, 996, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (556, 49, 1601, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (557, 176, 1507, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (558, 35, 2732, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (559, 92, 2155, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (560, 64, 1153, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (561, 50, 598, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (562, 190, 1163, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (563, 177, 2598, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (564, 36, 2235, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (565, 165, 2331, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (566, 71, 2910, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (567, 48, 2204, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (568, 57, 2089, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (569, 67, 2064, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (570, 49, 237, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (571, 101, 700, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (572, 153, 2777, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (573, 11, 154, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (574, 194, 1146, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (575, 186, 2186, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (576, 85, 890, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (577, 123, 1189, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (578, 167, 317, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (579, 161, 687, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (580, 53, 393, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (581, 42, 2868, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (582, 80, 1069, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (583, 82, 1858, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (584, 141, 314, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (585, 23, 2555, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (586, 152, 2038, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (587, 104, 383, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (588, 30, 1601, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (589, 199, 2962, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (590, 168, 2619, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (591, 16, 2315, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (592, 90, 2818, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (593, 79, 1420, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (594, 167, 1054, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (595, 116, 1060, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (596, 87, 1031, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (597, 186, 1580, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (598, 147, 2521, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (599, 143, 254, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (600, 194, 797, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (601, 33, 1152, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (602, 101, 2473, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (603, 103, 2486, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (604, 66, 2971, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (605, 125, 2146, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (606, 85, 2637, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (607, 94, 1708, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (608, 56, 1503, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (609, 128, 2807, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (610, 76, 2823, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (611, 173, 100, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (612, 81, 2482, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (613, 131, 1962, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (614, 156, 2801, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (615, 62, 858, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (616, 109, 2315, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (617, 189, 2619, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (618, 31, 449, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (619, 154, 195, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (620, 80, 693, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (621, 154, 2901, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (622, 31, 1503, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (623, 48, 263, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (624, 139, 308, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (625, 109, 1139, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (626, 17, 970, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (627, 106, 261, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (628, 47, 2840, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (629, 137, 2390, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (630, 195, 1055, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (631, 160, 1681, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (632, 154, 1754, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (633, 125, 2942, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (634, 197, 2379, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (635, 115, 2582, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (636, 6, 156, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (637, 44, 1279, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (638, 130, 686, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (639, 76, 1602, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (640, 39, 1702, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (641, 1, 927, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (642, 39, 2495, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (643, 47, 2731, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (644, 156, 2296, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (645, 194, 745, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (646, 192, 1435, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (647, 163, 261, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (648, 193, 2287, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (649, 116, 2061, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (650, 1, 1732, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (651, 81, 863, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (652, 140, 674, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (653, 167, 2053, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (654, 92, 2041, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (655, 47, 343, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (656, 197, 2880, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (657, 48, 2599, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (658, 95, 597, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (659, 43, 1851, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (660, 96, 2261, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (661, 128, 1920, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (662, 117, 633, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (663, 49, 1034, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (664, 196, 298, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (665, 196, 1995, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (666, 73, 1166, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (667, 8, 640, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (668, 23, 1360, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (669, 9, 2084, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (670, 130, 2481, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (671, 64, 942, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (672, 131, 2132, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (673, 181, 2450, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (674, 120, 801, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (675, 118, 2962, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (676, 83, 967, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (677, 111, 739, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (678, 82, 2510, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (679, 29, 2302, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (680, 82, 2223, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (681, 64, 2315, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (682, 124, 2761, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (683, 8, 1516, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (684, 195, 2858, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (685, 150, 1198, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (686, 199, 259, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (687, 51, 1503, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (688, 72, 1708, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (689, 47, 1764, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (690, 166, 953, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (691, 41, 1725, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (692, 129, 1468, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (693, 192, 1571, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (694, 62, 2960, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (695, 184, 1880, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (696, 162, 2146, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (697, 110, 1203, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (698, 99, 259, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (699, 198, 1762, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (700, 113, 2571, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (701, 95, 2835, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (702, 29, 1068, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (703, 142, 2560, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (704, 99, 2873, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (705, 155, 2201, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (706, 136, 1733, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (707, 197, 1350, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (708, 83, 2158, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (709, 15, 2536, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (710, 83, 1147, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (711, 19, 1193, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (712, 78, 219, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (713, 126, 486, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (714, 56, 2674, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (715, 123, 1153, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (716, 178, 426, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (717, 124, 1207, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (718, 86, 92, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (719, 31, 481, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (720, 179, 762, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (721, 184, 1939, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (722, 133, 2987, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (723, 39, 314, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (724, 9, 229, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (725, 9, 361, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (726, 140, 1503, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (727, 18, 677, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (728, 196, 1701, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (729, 66, 2540, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (730, 71, 1030, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (731, 70, 1514, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (732, 46, 1151, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (733, 142, 2221, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (734, 34, 623, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (735, 137, 770, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (736, 33, 1750, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (737, 143, 1707, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (738, 114, 185, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (739, 26, 2029, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (740, 75, 1558, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (741, 72, 2810, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (742, 91, 1104, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (743, 54, 743, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (744, 173, 1945, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (745, 8, 1206, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (746, 137, 2852, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (747, 22, 1642, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (748, 152, 1273, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (749, 162, 1403, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (750, 66, 816, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (751, 53, 1469, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (752, 57, 2054, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (753, 179, 315, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (754, 13, 1363, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (755, 173, 1791, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (756, 78, 430, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (757, 158, 490, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (758, 80, 235, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (759, 18, 483, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (760, 18, 2073, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (761, 114, 2853, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (762, 33, 2219, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (763, 22, 259, 'Tester');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (764, 52, 2106, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (765, 120, 2809, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (766, 195, 1566, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (767, 89, 1805, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (768, 103, 2622, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (769, 150, 2370, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (770, 46, 193, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (771, 3, 2085, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (772, 112, 2672, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (773, 149, 1428, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (774, 51, 1559, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (775, 189, 2526, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (776, 94, 2668, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (777, 197, 2772, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (778, 181, 1522, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (779, 146, 2876, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (780, 153, 1438, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (781, 20, 870, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (782, 196, 18, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (783, 151, 2896, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (784, 101, 2573, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (785, 12, 2277, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (786, 189, 2862, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (787, 103, 174, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (788, 8, 898, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (789, 126, 1564, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (790, 72, 2354, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (791, 191, 1915, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (792, 170, 2123, 'UI/UX');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (793, 167, 1300, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (794, 25, 756, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (795, 19, 713, 'Developer');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (796, 63, 1284, 'DevOps');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (797, 173, 1817, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (798, 6, 2223, 'Team Lead');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (799, 41, 1451, 'Documentation');
INSERT INTO team (team_id, project_id, student_id, role_in_team) VALUES (800, 144, 1260, 'Team Lead');